[package]
name = "eth-signer"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-core = { version = "2.0" }
ethers-signers = { version = "2.0" }
